export const productos = {
  procesadores: [
    { id: 1, nombre: 'Procesador Intel i9', descripcion: 'Descripción del procesador Intel i9', precio: 500, imagen: '/src/assets/Intel_Core_i9_2020_logo.svg.png' },
    { id: 2, nombre: 'Procesador AMD Ryzen 9', descripcion: 'Descripción del procesador AMD Ryzen 9', precio: 450, imagen: '/src/assets/amd_ryzen_9_7950x3d1.jpg' },
    { id: 3, nombre: 'Procesador Intel i7', descripcion: 'Descripción del procesador Intel i7', precio: 400, imagen: '/src/assets/corei7.jpg'},
    { id: 4, nombre: 'Procesador AMD Ryzen 7', descripcion: 'Descripción del procesador AMD Ryzen 7', precio: 350, imagen: '/src/assets/amd_ryzen_7.jpg'},
    { id: 5, nombre: 'Procesador Intel i5', descripcion: 'Descripción del procesador Intel i5', precio: 300, imagen: '/src/assets/intel_i5.jpg'},
    { id: 6, nombre: 'Procesador AMD Ryzen 5', descripcion: 'Descripción del procesador AMD Ryzen 5', precio: 250, imagen: '/src/assets/amd_ryzen_5.jpg'},
  ],
  placasVideo: [
    { id: 7, nombre: 'Placa de Video XFX Radeon RX 6650', descripcion: '8GB GDDR6', precio: 950, imagen: '/src/assets/compragamer_Imganen_general_33401_Placa_de_Video_XFX_Radeon_RX_6650_XT_8GB_GDDR6_Speedster_SWFT_210_589f396b-grn.jpg' },
    { id: 8, nombre: 'Placa de Video XFX Radeon RX 6750', descripcion: '12GB GDDR6', precio: 900, imagen: '/src/assets/radeom rx6750.jpg' },
    { id: 9, nombre: 'Placa de Video Nvidia RTX 3080', descripcion: '10GB GDDR6X', precio: 900, imagen: '/src/assets/nividia 3080.jpg'  },
    { id: 10, nombre: 'Placa de Video Nvidia RTX 3070', descripcion: '8GB GDDR6', precio: 800, imagen: '/src/assets/nvidia_3070.jpg'},
    { id: 11, nombre: 'Placa de Video AMD Radeon RX 6800', descripcion: '16GB GDDR6', precio: 850, imagen: '/src/assets/amd_rx_6800.jpg'},
    { id: 12, nombre: 'Placa de Video Nvidia RTX 3060', descripcion: '12GB GDDR6', precio: 700, imagen: '/src/assets/nvidia_3060.jpg'},
  ],
  motherboards: [
    { id: 13, nombre: 'Motherboard ASUS ROG', descripcion: 'Descripción de la motherboard ASUS ROG', precio: 200, imagen: '/src/assets/Mother board ASUSROG.jpg'},
    { id: 14, nombre: 'Motherboard MSI MPG', descripcion: 'Descripción de la motherboard MSI MPG', precio: 180, imagen: '/src/assets/motherboard MSI MPG.jpg' },
    { id: 15, nombre: 'Motherboard Gigabyte AORUS', descripcion: 'Descripción de la motherboard Gigabyte AORUS', precio: 220, imagen: '/src/assets/motherboard Gigabyte AORUS.jpg' },
    { id: 16, nombre: 'Motherboard ASRock Phantom', descripcion: 'Descripción de la motherboard ASRock Phantom', precio: 160, imagen: '/src/assets/motherboard_asrock_phantom.jpg'},
    { id: 17, nombre: 'Motherboard Biostar Racing', descripcion: 'Descripción de la motherboard Biostar Racing', precio: 140, imagen: '/src/assets/motherboard_biostar_racing.jpg'},
    { id: 18, nombre: 'Motherboard ASUS TUF', descripcion: 'Descripción de la motherboard ASUS TUF', precio: 190, imagen: '/src/assets/motherboard_asus_tuf.jpg'},
  ],
  memoriaRam: [
    { id: 19, nombre: 'Memoria RAM Corsair 16GB', descripcion: 'Descripción de la memoria RAM Corsair 16GB', precio: 150, imagen: '/src/assets/memoria RAM Corsair 16GB.jpg' },
    { id: 20, nombre: 'Memoria RAM Kingston 32GB', descripcion: 'Descripción de la memoria RAM Kingston 32GB', precio: 250, imagen: '/src/assets/memoria RAM Kingston 32GB.jpg' },
    { id: 21, nombre: 'Memoria RAM G.Skill 8GB', descripcion: 'Descripción de la memoria RAM G.Skill 8GB', precio: 80, imagen: '/src/assets/memoria RAM G.Skill 8GB.jpg' },
    { id: 22, nombre: 'Memoria RAM Crucial 16GB', descripcion: 'Descripción de la memoria RAM Crucial 16GB', precio: 140, imagen: '/src/assets/memoria_RAM_Crucial_16GB.jpg'},
    { id: 23, nombre: 'Memoria RAM HyperX 32GB', descripcion: 'Descripción de la memoria RAM HyperX 32GB', precio: 260, imagen: '/src/assets/memoria_RAM_HyperX_32GB.jpg'},
    { id: 24, nombre: 'Memoria RAM ADATA 8GB', descripcion: 'Descripción de la memoria RAM ADATA 8GB', precio: 70, imagen: '/src/assets/memoria_RAM_ADATA_8GB.jpg'},
  ],
  fuentes: [
    { id: 25, nombre: 'Fuente de Poder EVGA 750W', descripcion: 'Descripción de la fuente EVGA 750W', precio: 120, imagen: '/src/assets/fuente EVGA 750W.jpg' },
    { id: 26, nombre: 'Fuente de Poder Corsair 650W', descripcion: 'Descripción de la fuente Corsair 650W', precio: 100, imagen: '/src/assets/fuente Corsair 650W.jpg' },
    { id: 27, nombre: 'Fuente de Poder Seasonic 850W', descripcion: 'Descripción de la fuente Seasonic 850W', precio: 150, imagen: '/src/assets/fuente Seasonic 850W.jpg' },
    { id: 28, nombre: 'Fuente de Poder Thermaltake 600W', descripcion: 'Descripción de la fuente Thermaltake 600W', precio: 90, imagen: '/src/assets/fuente_Thermaltake_600W.jpg'},
    { id: 29, nombre: 'Fuente de Poder Gigabyte 700W', descripcion: 'Descripción de la fuente Gigabyte 700W', precio: 110, imagen: '/src/assets/fuente_Gigabyte_700W.jpg'},
    { id: 30, nombre: 'Fuente de Poder NZXT 850W', descripcion: 'Descripción de la fuente NZXT 850W', precio: 140, imagen: '/src/assets/fuente_NZXT_850W.jpg'},
  ],
  gabinetes: [
    { id: 31, nombre: 'Gabinete NZXT', descripcion: 'Descripción del gabinete NZXT', precio: 100, imagen: '/src/assets/gabinete NZXT.jpg' },
    { id: 32, nombre: 'Gabinete Cooler Master', descripcion: 'Descripción del gabinete Cooler Master', precio: 110, imagen: '/src/assets/Cooler Master.jpg' },
    { id: 33, nombre: 'Gabinete Corsair', descripcion: 'Descripción del gabinete Corsair', precio: 120, imagen: '/src/assets/gabinete Corsair.jpg' },
    { id: 34, nombre: 'Gabinete Thermaltake', descripcion: 'Descripción del gabinete Thermaltake', precio: 90, imagen: '/src/assets/gabinete_Thermaltake.jpg'},
    { id: 35, nombre: 'Gabinete Phanteks', descripcion: 'Descripción del gabinete Phanteks', precio: 130, imagen: '/src/assets/gabinete_Phanteks.jpg'},
    { id: 36, nombre: 'Gabinete Be Quiet!', descripcion: 'Descripción del gabinete Be Quiet!', precio: 140, imagen: '/src/assets/gabinete_Be_Quiet!.jpg'},
  ],
  refrigeracion: [
    { id: 37, nombre: 'Refrigeración líquida Cooler Master', descripcion: 'Descripción de la refrigeración Cooler Master', precio: 80, imagen: '/src/assets/refrigeración Cooler Master.jpg' },
    { id: 38, nombre: 'Refrigeración líquida NZXT', descripcion: 'Descripción de la refrigeración NZXT', precio: 90, imagen: '/src/assets/refrigeración NZXT.jpg' },
    { id: 39, nombre: 'Refrigeración por aire Noctua', descripcion: 'Descripción de la refrigeración Noctua', precio: 70, imagen: '/src/assets/refrigeración Noctua.jpg' },
    { id: 40, nombre: 'Refrigeración líquida Corsair', descripcion: 'Descripción de la refrigeración Corsair', precio: 85, imagen: '/src/assets/refrigeración_Corsair.jpg'},
    { id: 41, nombre: 'Refrigeración líquida Thermaltake', descripcion: 'Descripción de la refrigeración Thermaltake', precio: 95, imagen: '/src/assets/refrigeración_Thermaltake.jpg'},
    { id: 42, nombre: 'Refrigeración por aire Be Quiet!', descripcion: 'Descripción de la refrigeración Be Quiet!', precio: 75, imagen: '/src/assets/refrigeración_Be_Quiet!.jpg'},
  ],
  almacenamiento: [
    { id: 43, nombre: 'SSD Samsung 1TB', descripcion: 'Descripción del SSD Samsung 1TB', precio: 130, imagen: '/src/assets/SSD Samsung 1TB.jpg' },
    { id: 44, nombre: 'HDD Seagate 2TB', descripcion: 'Descripción del HDD Seagate 2TB', precio: 80, imagen: '/src/assets/HDD Seagate 2TB.jpg' },
    { id: 45, nombre: 'SSD Kingston 500GB', descripcion: 'Descripción del SSD Kingston 500GB', precio: 70, imagen: '/src/assets/SSD Kingston 500GB.jpg' },
    { id: 46, nombre: 'SSD Crucial 1TB', descripcion: 'Descripción del SSD Crucial 1TB', precio: 120, imagen: '/src/assets/SSD_Crucial_1TB.jpg'},
    { id: 47, nombre: 'HDD Western Digital 4TB', descripcion: 'Descripción del HDD Western Digital 4TB', precio: 150, imagen: '/src/assets/HDD_WD_4TB.jpg'},
    { id: 48, nombre: 'SSD Samsung 2TB', descripcion: 'Descripción del SSD Samsung 2TB', precio: 200, imagen: '/src/assets/SSD_Samsung_2TB.jpg'},
  ],
};

export const destacados = [
  { id: 4, nombre: 'Placa de Video XFX Radeon RX 6650', descripcion: '8GB GDDR6', precio: 950, imagen: '/src/assets/compragamer_Imganen_general_33401_Placa_de_Video_XFX_Radeon_RX_6650_XT_8GB_GDDR6_Speedster_SWFT_210_589f396b-grn.jpg' },
  { id: 2, nombre: 'Procesador AMD Ryzen 9', descripcion: 'Descripción del procesador AMD Ryzen 9', precio: 450, imagen: '/src/assets/amd_ryzen_9_7950x3d1.jpg' },
  { id: 19, nombre: 'Memoria RAM Corsair 16GB', descripcion: 'Descripción de la memoria RAM Corsair 16GB', precio: 150, imagen: '/src/assets/memoria RAM Corsair 16GB.jpg' },
  { id: 21, nombre: 'Memoria RAM G.Skill 8GB', descripcion: 'Descripción de la memoria RAM G.Skill 8GB', precio: 80, imagen: '/src/assets/memoria RAM G.Skill 8GB.jpg ' },
  { id: 24, nombre: 'Memoria RAM ADATA 8GB', descripcion: 'Descripción de la memoria RAM ADATA 8GB', precio: 70, imagen: '/src/assets/memoria_RAM_ADATA_8GB.jpg' },
  { id: 25, nombre: 'Fuente de Poder EVGA 750W', descripcion: 'Descripción de la fuente EVGA 750W', precio: 120, imagen: '/src/assets/fuente EVGA 750W.jpg' },
  { id: 28, nombre: 'Fuente de Poder Thermaltake 600W', descripcion: 'Descripción de la fuente Thermaltake 600W', precio: 90, imagen: '/src/assets/fuente_Thermaltake_600W.jpg'},
  { id: 30, nombre: 'Fuente de Poder NZXT 850W', descripcion: 'Descripción de la fuente NZXT 850W', precio: 140, imagen: '/src/assets/fuente_NZXT_850W.jpg'},
  { id: 32, nombre: 'Gabinete Cooler Master', descripcion: 'Descripción del gabinete Cooler Master', precio: 110, imagen: '/src/assets/Cooler Master.jpg' },
  { id: 34, nombre: 'Gabinete Thermaltake', descripcion: 'Descripción del gabinete Thermaltake', precio: 90, imagen: '/src/assets/gabinete_Thermaltake.jpg'},
  { id: 36, nombre: 'Gabinete Be Quiet!', descripcion: 'Descripción del gabinete Be Quiet!', precio: 140, imagen: '/src/assets/gabinete_Be_Quiet!.jpg'},
  { id: 44, nombre: 'HDD Seagate 2TB', descripcion: 'Descripción del HDD Seagate 2TB', precio: 80, imagen: '/src/assets/HDD Seagate 2TB.jpg' },
  { id: 46, nombre: 'SSD Crucial 1TB', descripcion: 'Descripción del SSD Crucial 1TB', precio: 120, imagen: '/src/assets/SSD_Crucial_1TB.jpg'},
  { id: 48, nombre: 'SSD Samsung 2TB', descripcion: 'Descripción del SSD Samsung 2TB', precio: 200, imagen: '/src/assets/SSD_Samsung_2TB.jpg'},
  { id: 40, nombre: 'Refrigeración líquida Corsair', descripcion: 'Descripción de la refrigeración Corsair', precio: 85, imagen: '/src/assets/refrigeración_Corsair.jpg'},
];